import Image from "next/image";

import {
    StyledTextContainer,
    StyledContainer,
    StyledTitle,
    StyledDescription,
    StyledMainContainer,
    StyledBackgroundImageContainer,
    StyledContentContainer,
    StyledSectionContainer,
    StyledVideoContainer,
    StyledCardContainer,
    StyledCard,
    StyledCardPicContainer,
    StyledCardTextContainer,
    StyledCardHeading,
    StyledCardDescription,
    StyledCardBoldText,
} from "./elements";

export const Selection = ({ ...props }) => {
    return (
        <StyledContainer {...props}>
            <StyledTextContainer>
                <StyledTitle>{props.title}</StyledTitle>
                <StyledDescription>{props.description}</StyledDescription>
            </StyledTextContainer>
            <StyledMainContainer>
                <StyledBackgroundImageContainer
                    width={props.image.width}
                    height={props.image.height}
                >
                    <StyledContentContainer>
                        <StyledSectionContainer>
                            <StyledVideoContainer>
                                <Image
                                    layout="responsive"
                                    src={props.videoProps.src}
                                    alt={props.videoProps.alt}
                                    width={props.videoProps.width}
                                    height={props.videoProps.height}
                                />
                            </StyledVideoContainer>
                        </StyledSectionContainer>
                        <StyledCardContainer>
                            <StyledCard
                                size={props.cardSize.small}
                                bgColor={props.cardBackGroundColor.light}
                            >
                                <StyledCardPicContainer>
                                    <Image
                                        src={props.brief.src}
                                        alt={props.brief.alt}
                                        width={props.iconWidth}
                                        height={props.iconHeight}
                                    />
                                </StyledCardPicContainer>
                                <StyledCardTextContainer>
                                    <StyledCardHeading>
                                        {props.contentFirstCard.title}
                                    </StyledCardHeading>
                                    <StyledCardDescription>
                                        {props.contentFirstCard.start}
                                        <StyledCardBoldText>
                                            {props.contentFirstCard.bold}
                                        </StyledCardBoldText>
                                        {props.contentFirstCard.end}
                                    </StyledCardDescription>
                                </StyledCardTextContainer>
                            </StyledCard>
                            <StyledCard
                                size={props.cardSize.medium}
                                bgColor={props.cardBackGroundColor.medium}
                            >
                                <StyledCardPicContainer>
                                    <Image
                                        src={props.search.src}
                                        alt={props.search.alt}
                                        width={props.iconWidth}
                                        height={props.iconHeight}
                                    />
                                </StyledCardPicContainer>
                                <StyledCardTextContainer>
                                    <StyledCardHeading>
                                        {props.contentSecondCard.title}
                                    </StyledCardHeading>
                                    <StyledCardDescription>
                                        {props.contentSecondCard.start}
                                        <StyledCardBoldText>
                                            {props.contentSecondCard.bold}
                                        </StyledCardBoldText>
                                        {props.contentSecondCard.end}
                                    </StyledCardDescription>
                                </StyledCardTextContainer>
                            </StyledCard>
                            <StyledCard
                                size={props.cardSize.big}
                                bgColor={props.cardBackGroundColor.dark}
                            >
                                <StyledCardPicContainer>
                                    <Image
                                        src={props.pitch.src}
                                        alt={props.pitch.alt}
                                        width={props.iconWidth}
                                        height={props.iconHeight}
                                    />
                                </StyledCardPicContainer>
                                <StyledCardTextContainer>
                                    <StyledCardHeading>
                                        {props.contentThirdCard.title}
                                    </StyledCardHeading>
                                    <StyledCardDescription>
                                        {props.contentThirdCard.start}
                                        <StyledCardBoldText>
                                            {props.contentThirdCard.bold}
                                        </StyledCardBoldText>
                                        {props.contentThirdCard.end}
                                    </StyledCardDescription>
                                </StyledCardTextContainer>
                            </StyledCard>
                        </StyledCardContainer>
                    </StyledContentContainer>
                </StyledBackgroundImageContainer>
            </StyledMainContainer>
        </StyledContainer>
    );
};
